import type { Achievement, Goal, ProgressEntry, ShopItem, User } from "./types";

export const mockUser: User = {
  id: "u_1",
  name: "Jordan Avery",
  username: "jordana",
  email: "jordan@example.com",
  level: 7,
  currentXp: 340,
  xpToNextLevel: 600,
  totalXp: 4340,
  points: 1280,
  streakDays: 12,
  joinedAt: "2026-03-02T00:00:00.000Z",
  avatarSeed: "jordan-01",
};

export const mockGoals: Goal[] = [
  {
    id: "g_1",
    title: "Run a sub-25-minute 5K",
    description: "Build up weekly mileage and speed work to break 25 minutes on a real race.",
    category: "fitness",
    difficulty: "medium",
    status: "in_progress",
    target: 25,
    unit: "min (lower is better)",
    currentValue: 27.4,
    deadline: "2026-10-15T00:00:00.000Z",
    createdAt: "2026-07-01T00:00:00.000Z",
    xpReward: 220,
    milestones: [
      { id: "m_1", title: "Run 3x per week for a month", isComplete: true },
      { id: "m_2", title: "Break 26:30", isComplete: true },
      { id: "m_3", title: "Break 25:45", isComplete: false },
      { id: "m_4", title: "Race day: sub-25:00", isComplete: false },
    ],
  },
  {
    id: "g_2",
    title: "Finish CS50 coursework",
    description: "Complete all problem sets and the final project for CS50.",
    category: "academic",
    difficulty: "hard",
    status: "in_progress",
    target: 12,
    unit: "problem sets",
    currentValue: 8,
    deadline: "2026-09-30T00:00:00.000Z",
    createdAt: "2026-05-12T00:00:00.000Z",
    xpReward: 400,
    milestones: [
      { id: "m_5", title: "Complete weeks 1-4", isComplete: true },
      { id: "m_6", title: "Complete weeks 5-8", isComplete: true },
      { id: "m_7", title: "Submit final project", isComplete: false },
    ],
  },
  {
    id: "g_3",
    title: "Save $2,000 emergency fund",
    description: "Automate transfers and cut discretionary spending until the fund is fully built.",
    category: "finance",
    difficulty: "medium",
    status: "active",
    target: 2000,
    unit: "USD saved",
    currentValue: 650,
    deadline: "2026-12-31T00:00:00.000Z",
    createdAt: "2026-08-10T00:00:00.000Z",
    xpReward: 260,
    milestones: [
      { id: "m_8", title: "Reach $500", isComplete: true },
      { id: "m_9", title: "Reach $1,200", isComplete: false },
      { id: "m_10", title: "Reach $2,000", isComplete: false },
    ],
  },
  {
    id: "g_4",
    title: "Read 6 books this quarter",
    description: "A mix of fiction and non-fiction, at least 20 minutes a day.",
    category: "personal",
    difficulty: "easy",
    status: "completed",
    target: 6,
    unit: "books",
    currentValue: 6,
    deadline: "2026-08-01T00:00:00.000Z",
    createdAt: "2026-05-01T00:00:00.000Z",
    xpReward: 150,
    milestones: [
      { id: "m_11", title: "Finish first 3 books", isComplete: true },
      { id: "m_12", title: "Finish all 6 books", isComplete: true },
    ],
  },
];

export const mockProgressEntries: ProgressEntry[] = [
  { id: "p_1", goalId: "g_1", value: 27.4, note: "Tempo run, felt strong", loggedAt: "2026-08-24T09:15:00.000Z" },
  { id: "p_2", goalId: "g_2", value: 8, note: "Finished problem set 8", loggedAt: "2026-08-23T20:00:00.000Z" },
  { id: "p_3", goalId: "g_3", value: 650, note: "Payday transfer", loggedAt: "2026-08-20T12:00:00.000Z" },
];

export const mockAchievements: Achievement[] = [
  {
    id: "a_1",
    title: "First Steps",
    description: "Create your very first goal.",
    requirement: "Create 1 goal",
    rarity: "common",
    xpReward: 20,
    isUnlocked: true,
    unlockedAt: "2026-03-02T00:00:00.000Z",
    icon: "flag",
  },
  {
    id: "a_2",
    title: "On a Roll",
    description: "Keep a 7-day activity streak alive.",
    requirement: "7-day streak",
    rarity: "common",
    xpReward: 50,
    isUnlocked: true,
    unlockedAt: "2026-06-14T00:00:00.000Z",
    icon: "flame",
  },
  {
    id: "a_3",
    title: "Finisher",
    description: "Complete your first goal.",
    requirement: "Complete 1 goal",
    rarity: "rare",
    xpReward: 100,
    isUnlocked: true,
    unlockedAt: "2026-08-01T00:00:00.000Z",
    icon: "trophy",
  },
  {
    id: "a_4",
    title: "Marathon Mindset",
    description: "Keep a 30-day activity streak alive.",
    requirement: "30-day streak",
    rarity: "epic",
    xpReward: 300,
    isUnlocked: false,
    icon: "flame",
  },
  {
    id: "a_5",
    title: "Renaissance",
    description: "Complete a goal in five different categories.",
    requirement: "5 categories completed",
    rarity: "legendary",
    xpReward: 500,
    isUnlocked: false,
    icon: "star",
  },
];

export const mockShopItems: ShopItem[] = [
  { id: "s_1", name: "Slate Hoodie", description: "A calm, focused look.", category: "clothing", cost: 200, isOwned: true },
  { id: "s_2", name: "Violet Cape", description: "For goals that deserve a flourish.", category: "clothing", cost: 450, isOwned: false },
  { id: "s_3", name: "Compass Pin", description: "Never lose sight of the target.", category: "accessory", cost: 150, isOwned: false },
  { id: "s_4", name: "Ember Trail", description: "A subtle trail effect on level-up.", category: "effect", cost: 600, isOwned: false },
];
